[workspace]
name = "workshop_intro_to_bia_napari"
version = "0.1.0"
description = "Entorno unificado para microglía - UPCH"
authors = ["Agustin Corbat <acorbat.bia@gmail.com>"]
channels = ["conda-forge", "pytorch"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[feature.cellpose.target.win.dependencies]
pytorch = {version = "*", build = "cpu*"}

[feature.cellpose.dependencies]
python = "3.11.*"
napari = ">=0.5.0"
cellpose = "*"
stardist = "*"
bioio = "*"
jupyterlab = "*"

[feature.assistant.dependencies]
python = "3.10.*"
napari = ">=0.5.0"
napari-assistant = "*"
napari-pyclesperanto-assistant = "*"
scikit-image = "*"
numpy = "*"
napari-segment-blobs-and-things-with-membranes = "*"
napari-skimage-regionprops = "*"
pyqt = "*"

[environments]
assistant = ["assistant", "default"]
cellpose = ["cellpose", "default"]

[feature.assistant.tasks]
assistant = "napari"
napari = { cmd = "python -m napari", env = { PYOPENCL_NO_CACHE = "1" } }
reset = "napari --reset"

[dependencies]
pyclesperanto-prototype = "*"
napari-aicsimageio = "*"
aicspylibczi = "*"
xmlschema = "*"
tifffile = "==2023.4.12"
fsspec = "*"